//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryBook
    {
        public int BookId { get; set; }
        public int BookCategoryId { get; set; }
        public string BookTitle { get; set; }
        public string BookPublishYear { get; set; }
        public System.DateTime DateTime { get; set; }
        public string BookImage { get; set; }
        public string BookAuthor { get; set; }
    
        public virtual LibraryBookCategory LibraryBookCategory { get; set; }
    }
}
